apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 375147793846.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 2ee8f7d0
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
